require conf/distro/poky.conf

DISTRO = "fourcat"
DISTRO_NAME = "Fourcat (based on Poky Distro)"
DISTRO_VERSION = "1.0"

# The raspberrypi build depends on non-free firmware that includes the Synaptics license.
LICENSE_FLAGS_ACCEPTED += "synaptics-killswitch"

DISTRO_FEATURES:append = " bluetooth"

PACKAGECONFIG:append:pn-bluez5 = " tools"